/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as PromptsCreateRouteImport } from './routes/prompts/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsCreateRoute = PromptsCreateRouteImport.update({
  id: '/prompts/create',
  path: '/prompts/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompts/create': typeof PromptsCreateRoute
  '/prompts/': typeof PromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompts/create': typeof PromptsCreateRoute
  '/prompts': typeof PromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompts/create': typeof PromptsCreateRoute
  '/prompts/': typeof PromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prompts/create' | '/prompts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prompts/create' | '/prompts'
  id: '__root__' | '/' | '/prompts/create' | '/prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptsCreateRoute: typeof PromptsCreateRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/create': {
      id: '/prompts/create'
      path: '/prompts/create'
      fullPath: '/prompts/create'
      preLoaderRoute: typeof PromptsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptsCreateRoute: PromptsCreateRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
